/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "dev-lake-utils"
rootProject.buildFileName = "dev-lake-utils.gradle.kts"

include("summary-publisher")
project(":summary-publisher").buildFileName = "summary-publisher.gradle.kts"
include("utilities")
project(":utilities").buildFileName = "utilities.gradle.kts"
include("user-metrics-publisher")
project(":user-metrics-publisher").buildFileName = "user-metrics-publisher.gradle.kts"
include("github-control-panel")
project(":github-control-panel").buildFileName = "github-control-panel.gradle.kts"
