package com.github.karlsabo.git

internal const val SETUP_COMMAND_START_MARKER = "__ENG_HUB_SETUP_COMMAND_STARTED__"
internal const val SETUP_COMMAND_RESULT_MARKER = "__ENG_HUB_SETUP_COMMAND_RESULT__"
internal const val SETUP_COMMAND_FAILURE_MARKER = "__ENG_HUB_SETUP_COMMAND_FAILED__"
internal const val SETUP_COMMAND_STDOUT_BEGIN_MARKER = "__ENG_HUB_SETUP_COMMAND_STDOUT_BEGIN__"
internal const val SETUP_COMMAND_STDOUT_END_MARKER = "__ENG_HUB_SETUP_COMMAND_STDOUT_END__"
internal const val SETUP_COMMAND_STDERR_BEGIN_MARKER = "__ENG_HUB_SETUP_COMMAND_STDERR_BEGIN__"
internal const val SETUP_COMMAND_STDERR_END_MARKER = "__ENG_HUB_SETUP_COMMAND_STDERR_END__"
